import { Imovie } from "../models/movie"




export const movieData: Imovie[]= [

  {
    adult: false,
    backdrop_path: '/8YFL5QQVPy3AgrEQxNYVSgiPEbe.jpg',
    genre_ids: [28, 12, 878],
    id: 640146,
    original_language: 'en',
    original_title: 'Ant-Man and the Wasp: Quantumania',
    overview: 'Super-Hero partners Scott Lang and Hope van Dyne, along with Hope\'s parents Janet van Dyne and Hank Pym, and Scott\'s daughter Cassie Lang, explore the Quantum Realm, interacting with strange new creatures and embarking on an adventure beyond what they thought possible.',
    popularity: 8234.134,
    poster_path: '/ng12FKB1U4fhbdsrtdom9LVLBXw.jpg',
    release_date: '2023-02-17',
    title: 'Ant-Man and the Wasp: Quantumania',
    video: false,
    vote_average: 6.5,
    vote_count: 1233
  },
  {
    adult: false,
    backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    genre_ids: [18, 80],
    id: 238,
    original_language: 'en',
    original_title: 'The Godfather',
    overview: 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family.',
    popularity: 623.134,
    poster_path: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    release_date: '1972-03-14',
    title: 'The Godfather',
    video: false,
    vote_average: 8.7,
    vote_count: 18333
  },
  {
    adult: false,
    backdrop_path: '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
    genre_ids: [53, 80],
    id: 680,
    original_language: 'en',
    original_title: 'Pulp Fiction',
    overview: 'The lives of two mob hitmen, a boxer, a gangster\'s wife, and a pair of diner bandits intertwine in tales of violence and redemption.',
    popularity: 531.124,
    poster_path: '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    release_date: '1994-09-10',
    title: 'Pulp Fiction',
    video: false,
    vote_average: 8.5,
    vote_count: 24833
  },

  {
    adult: false,
    backdrop_path: "/m2hs6YPVrzjvRC21SE9BeXtgqFW.jpg",
    genre_ids: [16, 9648, 878, 28],
    id: 1299652,
    original_language: "en",
    original_title: "Watchmen: Chapter II",
    overview: "Suspicious of the events ensnaring their former colleagues, Nite Owl and Silk Spectre are spurred out of retirement to investigate. As they grapple with personal ethics, inner demons and a society turned against them, they race the clock to uncover a deepening plot that might trigger global nuclear war.",
    popularity: 1226.19,
    poster_path: "/4rBObJFpiWJOG7aIlRrOUniAkBs.jpg",
    release_date: "2024-11-25",
    title: "Watchmen: Chapter II",
    video: false,
    vote_average: 4.6,
    vote_count: 49
  },
  {
    adult: false,
    backdrop_path: "/euYIwmwkmz95mnXvufEmbL6ovhZ.jpg",
    genre_ids: [28, 12, 36],
    id: 558449,
    original_language: "en",
    original_title: "Gladiator II",
    overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart, the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
    popularity: 1105.753,
    poster_path: "/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    release_date: "2024-11-05",
    title: "Gladiator II",
    video: false,
    vote_average: 6.7,
    vote_count: 1094
  },
  {
    adult: false,
    backdrop_path: "/rhc8Mtuo3Kh8CndnlmTNMF8o9pU.jpg",
    genre_ids: [28, 53],
    id: 1005331,
    original_language: "en",
    original_title: "Carry-On",
    overview: "An airport security officer races to outsmart a mysterious traveler forcing him to let a dangerous item slip onto a Christmas Eve flight.",
    popularity: 2430.202,
    poster_path: "/sjMN7DRi4sGiledsmllEw5HJjPy.jpg",
    release_date: "2024-12-05",
    title: "Carry-On",
    video: false,
    vote_average: 7.0,
    vote_count: 1027
  },
  {
    adult: false,
    backdrop_path: "/9REO1DLpmwhrBJY3mYW5eVxkXFM.jpg",
    genre_ids: [12, 18, 878],
    id: 157336,
    original_language: "en",
    original_title: "Interstellar",
    overview: "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
    popularity: 404.256,
    poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    release_date: "2014-11-05",
    title: "Interstellar",
    video: false,
    vote_average: 8.445,
    vote_count: 35887
  },
  {
    adult: false,
    backdrop_path: "/Ar7QuJ7sJEiC0oP3I8fKBKIQD9u.jpg",
    genre_ids: [28, 18, 12],
    id: 98,
    original_language: "en",
    original_title: "Gladiator",
    overview: "After the death of Emperor Marcus Aurelius, his devious son takes power and demotes Maximus, one of Rome's most capable generals who Marcus preferred. Eventually, Maximus is forced to become a gladiator and battle to the death against other men for the amusement of paying audiences.",
    popularity: 444.195,
    poster_path: "/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    release_date: "2000-05-04",
    title: "Gladiator",
    video: false,
    vote_average: 8.2,
    vote_count: 18785
  },
  {
    adult: false,
    backdrop_path: "/zb6fM1CX41D9rF9hdgclu0peUmy.jpg",
    genre_ids: [18, 36, 10752],
    id: 424,
    original_language: "en",
    original_title: "Schindler's List",
    overview: "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves.",
    popularity: 50.075,
    poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    release_date: "1993-12-15",
    title: "Schindler's List",
    video: false,
    vote_average: 8.6,
    vote_count: 14698
  },
  {
    adult: false,
    backdrop_path: "/dqK9Hag1054tghRQSqLSfrkvQnA.jpg",
    genre_ids: [18, 28, 80, 53],
    id: 155,
    original_language: "en",
    original_title: "The Dark Knight",
    overview: "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
    popularity: 90.632,
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    release_date: "2008-07-16",
    title: "The Dark Knight",
    video: false,
    vote_average: 8.5,
    vote_count: 30796
  },
  {
    adult: false,
    backdrop_path: "/vI3aUGTuRRdM7J78KIdW98LdxE5.jpg",
    genre_ids: [35, 18, 10749],
    id: 19404,
    original_language: "hi",
    original_title: "दिलवाले दुल्हनिया ले जायेंगे",
    overview: "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
    popularity: 42.644,
    poster_path: "/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg",
    release_date: "1995-10-20",
    title: "Dilwale Dulhania Le Jayenge",
    video: false,
    vote_average: 8.525,
    vote_count: 4442
  },
  {
    adult: false,
    backdrop_path: "/vI3aUGTuRRdM7J78KIdW98LdxE5.jpg",
    genre_ids: [12, 28, 14],
    id: 497,
    original_language: "en",
    original_title: "The Green Mile",
    overview: "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes his miraculous gift, he tries desperately to help stave off the condemned man’s execution.",
    popularity: 62.841,
    poster_path: "/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg",
    release_date: "1999-12-10",
    title: "The Green Mile",
    video: false,
    vote_average: 8.5,
    vote_count: 19045
  },
  {
    adult: false,
    backdrop_path: "/5JrZAtyk3LwiiAWLW0kwz41XZJC.jpg",
    genre_ids: [12, 14, 28],
    id: 122,
    original_language: "en",
    original_title: "The Lord of the Rings: The Return of the King",
    overview: "As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies a brave hobbit, Frodo, who accompanied by his loyal friends must make a final stand against the shadows of Mordor.",
    popularity: 120.743,
    poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    release_date: "2003-12-01",
    title: "The Lord of the Rings: The Return of the King",
    video: false,
    vote_average: 8.481,
    vote_count: 23560
  },

  {
    adult: false,
    backdrop_path: "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    genre_ids: [18, 80],
    id: 238,
    original_language: "en",
    original_title: "The Godfather",
    overview: "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family.",
    popularity: 90.865,
    poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    release_date: "1972-03-14",
    title: "The Godfather",
    video: false,
    vote_average: 8.7,
    vote_count: 18312
  },
  {
    adult: false,
    backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    genre_ids: [53, 80],
    id: 680,
    original_language: "en",
    original_title: "Pulp Fiction",
    overview: "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in tales of violence and redemption.",
    popularity: 70.583,
    poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    release_date: "1994-09-10",
    title: "Pulp Fiction",
    video: false,
    vote_average: 8.5,
    vote_count: 24945
  },
  {
    adult: false,
    backdrop_path: "/vI3aUGTuRRdM7J78KIdW98LdxE5.jpg",
    genre_ids: [18, 36, 10752],
    id: 424,
    original_language: "en",
    original_title: "Schindler's List",
    overview: "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves.",
    popularity: 43.062,
    poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    release_date: "1993-12-15",
    title: "Schindler's List",
    video: false,
    vote_average: 8.6,
    vote_count: 14568
  },
  {
    adult: false,
    backdrop_path: "/dqK9Hag1054tghRQSqLSfrkvQnA.jpg",
    genre_ids: [28, 18, 80, 53],
    id: 155,
    original_language: "en",
    original_title: "The Dark Knight",
    overview: "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. When the era of the Joker dawns, chaos becomes the ultimate weapon.",
    popularity: 67.324,
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    release_date: "2008-07-16",
    title: "The Dark Knight",
    video: false,
    vote_average: 8.5,
    vote_count: 30576
  },
  {
    adult: false,
    backdrop_path: "/Ar7QuJ7sJEiC0oP3I8fKBKIQD9u.jpg",
    genre_ids: [28, 12, 14],
    id: 497,
    original_language: "en",
    original_title: "The Green Mile",
    overview: "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes his miraculous gift, he tries desperately to help stave off the condemned man’s execution.",
    popularity: 48.732,
    poster_path: "/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg",
    release_date: "1999-12-10",
    title: "The Green Mile",
    video: false,
    vote_average: 8.5,
    vote_count: 19040
  }
];


